name: pipeline

on: 
  push:
    branches: [develop]
  
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Build system
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Quality verification
        run: |
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with unit
        run: |
          py -m unittest discover tests